# Generated by Django 5.1.4 on 2025-01-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="links",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.projectlinks"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.projecttags"
            ),
        ),
    ]
