# Generated by Django 5.1.4 on 2025-01-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_links_alter_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
    ]
