# Generated by Django 5.1.4 on 2025-08-08 07:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['platform_name'],
            },
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Playing', 'Playing'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Planned', 'Planned'), ('On Hold', 'On Hold')], default='Planned', max_length=10)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=255)),
                ('started', models.DateField()),
                ('finished', models.DateField(blank=True, null=True)),
                ('t_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('h_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('play_time', models.DurationField()),
                ('body', models.TextField()),
                ('genre', models.TextField()),
                ('franchise', models.TextField()),
                ('series', models.TextField()),
                ('estimated_play_time', models.DurationField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapbook.gameplatform')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapbook.gamestatus')),
            ],
            options={
                'verbose_name': 'Game Entry',
                'verbose_name_plural': 'Game Entries',
                'ordering': ['game_title'],
            },
        ),
    ]
