# Generated by Django 5.1.4 on 2025-08-08 07:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameentry',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='estimated_play_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='franchise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='h_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scrapbook.gameplatform'),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='play_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='t_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
