# Generated by Django 5.1.4 on 2025-08-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0002_alter_gameentry_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='igdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
