# Generated by Django 5.1.4 on 2025-01-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="summary",
            field=models.TextField(default="Summary Text"),
            preserve_default=False,
        ),
    ]
