# Generated by Django 5.1.4 on 2025-01-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
